config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit this friend" if @friend.nil?
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
    @about_me = "Bobby"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="mb-3">
  <div class="form-label">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-text" %>
  </div>

  <div class="form-label">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-text" %>
  </div>

  <div class="form-label">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-text" %>
  </div>

  <div class="form-label">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-text" %>
  </div>

  <div class="form-label">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-text" %>
  </div>
  <div class="form-label">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-text", value: current_user.id, type: :hidden %>
  </div>
  <%=  %>
  <div>
    <%= form.submit class:"btn btn-primary" %>
  </div>
</div>
</form>

<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br>
<%= render "form", friend: @friend %>


<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
    <h1>Friends</h1>

    <div id="friends">
        <table class="table  table-stripped table-bordered table-hover text-center">
            <thead class="table-dark">
                <tr>
                    <th>
                        Name
                    </th>

                    <th>
                        Email
                    </th>
                    <th>
                        Phone
                    </th>
                    <th>
                        Twitter
                    </th>

                    <th colspan="3">Action</th>
                </tr>
            </thead>
            <tbody>
                <% @friends.each do |friend| %>
                    <% if friend.user == current_user%>
                        <tr>
                            <td>
                            <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
                            </td>
                            <td><%= friend.email%></td>
                            <td><%= friend.phone%></td>
                            <td><%= friend.twitter%></td>
                            <td><%= link_to 'Destroy', friend, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %></td>


                        </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>

    <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
<% else %>
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">Friends List App</h1>
                    <h2 class="text-black-50 mx-auto mt-2 mb-5">A Simple Application to log a list of contacts.</h2>
                    <a class="btn btn-primary" href="https://guides.rubyonrails.org/4_0_release_notes.html">Built on Ruby On Rails 7</a>
                </div>
            </div>
        </div>
    </header>
    <%end%>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div class="btn btn-dark">
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<div class="container-fluid bg-dark text-light p-5">
    <div class="container bg-dark p-5">

        <h1><%= @friend.first_name%>
            <%= @friend.last_name%>
        </h1>
        <hr>
            <p><%= @friend.email%></p>
            <p><%= @friend.phone%></p>
            <p><%= @friend.twitter%></p>

            <table>
                <tr>
                    <td>
                        <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-primary" %>
                        <td><%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
                        </td>
                        <td>
                            <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger" %></td>
                    </tr>
                </table>

            </div>
        </div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Friends App", root_path, class:"navbar-brand"%>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                <% if user_signed_in? %>
                                    <li class="nav-item">
                        <%= link_to "Show Friends", friends_path, class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "New Friends", new_friend_path, class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
                    </li>
                <% else %>
                 <li class="nav-item">
                        <%= link_to "Show Friends", friends_path, class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
                    </li>
                <% end %>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

app/views/home/about.erb
<h1> about </h1>

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
            <meta
                name="viewport" content="width=device-width, initial-scale=1">

                <!-- Bootstrap CSS -->
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

                    <title>FriendsAppRor</title>
                    <%= csrf_meta_tags %>
                    <%= csp_meta_tag %>

                    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
                    <%= javascript_importmap_tags %>
                </head>
                <body>
                    <!-- Optional JavaScript; choose one of the two! -->

                    <!-- Option 1: Bootstrap Bundle with Popper --><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"> </script>

                    <!-- Option 2: Separate Popper and Bootstrap JS -->
                    <!--
                        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
                        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
                        -->
                    <%= render 'home/header' %>
                    <div class="container">
                    <br/>
                        <% if notice  %>
                            <%= render 'layouts/alerts' %>
                        <% end %>
                        <br/>
                        <%= yield %>
                    </div>
                </body>
            </html>